### ISSUE TITLE
Getting TypeError: Cannot assign to read only property 'animation' of object '#<Object>' when running jest test

### ISSUE THREAD

**Issue by jtstodola** [superchenwb/react-native-linear-animated-gradient-transition#6]
```
TypeError: Cannot assign to read only property 'animation' of object '#<Object>'

      at getDerivedStateFromProps (node_modules/react-native-linear-animated-gradient-transition/lib/commonjs/index.tsx:48:8)
      at applyDerivedStateFromProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3857:22)
      at mountClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4266:5)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8310:5)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10076:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14694:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14667:22)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14366:11)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2063:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:818:12)
```

**Comment by jtstodola** [comment]
It looks like this can be fixed by adding the following to the bottom of the `src/index.tsx`
```
AnimatedGradientTransition.defaultProps = {
  colors: [],
  animation: {
    toValue: 1,
    duration: 500,
    easing: Easing.linear,
    useNativeDriver: true,
  },
}
```
